name: Create Tag and Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the new release'
        required: true

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  changelog:
    name: Build Changelog
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.build_changelog.outputs.changelog }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          token: ${{ github.TOKEN }}

  release:
    name: Release
    needs: changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ github.TOKEN }}
          tag_name: ${{ github.ref }}
          prerelease: false
          draft: false
          #files: bin/*
          generate_release_notes: true
          name: ${{ github.ref }}
          body: |
            <details>
              <summary>🤖 Autogenerated Conventional Changelog</summary>

            ${{ needs.changelog.outputs.changelog }}
            </details>
